"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, field_validator
from typing import Any, Optional
from typing_extensions import Annotated
from clientapi_pmg.models.nodes_tracker_list_mails_response import NodesTrackerListMailsResponse
from clientapi_pmg.models.nodes_tracker_maillog_response import NodesTrackerMaillogResponse

from clientapi_pmg.api_client import ApiClient, RequestSerialized
from clientapi_pmg.api_response import ApiResponse
from clientapi_pmg.rest import RESTResponseType


class NodesTrackerApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def list_mails(
        self,
        node: Annotated[str, Field(strict=True, description="The cluster node name.")],
        endtime: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.")] = None,
        var_from: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]], Field(description="Sender email address filter.")] = None,
        greylist: Annotated[Optional[Any], Field(description="Include Greylisted entries.")] = None,
        ndr: Annotated[Optional[Any], Field(description="Include NDRs (non delivery reports).")] = None,
        starttime: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.")] = None,
        target: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]], Field(description="Receiver email address filter.")] = None,
        xfilter: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]], Field(description="Only include mails containing this filter string.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NodesTrackerListMailsResponse:
        """Read mail list

        Read mail list.

        :param node: The cluster node name. (required)
        :type node: str
        :param endtime: Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.
        :type endtime: int
        :param var_from: Sender email address filter.
        :type var_from: str
        :param greylist: Include Greylisted entries.
        :type greylist: PmgBoolean
        :param ndr: Include NDRs (non delivery reports).
        :type ndr: PmgBoolean
        :param starttime: Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.
        :type starttime: int
        :param target: Receiver email address filter.
        :type target: str
        :param xfilter: Only include mails containing this filter string.
        :type xfilter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_mails_serialize(
            node=node,
            endtime=endtime,
            var_from=var_from,
            greylist=greylist,
            ndr=ndr,
            starttime=starttime,
            target=target,
            xfilter=xfilter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NodesTrackerListMailsResponse",
            '400': "PmgError",
            '401': "PmgError",
            '403': "PmgError",
            '404': "PmgError",
            '500': "PmgError",
            '501': "PmgError",
            '503': "PmgError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_mails_with_http_info(
        self,
        node: Annotated[str, Field(strict=True, description="The cluster node name.")],
        endtime: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.")] = None,
        var_from: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]], Field(description="Sender email address filter.")] = None,
        greylist: Annotated[Optional[Any], Field(description="Include Greylisted entries.")] = None,
        ndr: Annotated[Optional[Any], Field(description="Include NDRs (non delivery reports).")] = None,
        starttime: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.")] = None,
        target: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]], Field(description="Receiver email address filter.")] = None,
        xfilter: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]], Field(description="Only include mails containing this filter string.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NodesTrackerListMailsResponse]:
        """Read mail list

        Read mail list.

        :param node: The cluster node name. (required)
        :type node: str
        :param endtime: Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.
        :type endtime: int
        :param var_from: Sender email address filter.
        :type var_from: str
        :param greylist: Include Greylisted entries.
        :type greylist: PmgBoolean
        :param ndr: Include NDRs (non delivery reports).
        :type ndr: PmgBoolean
        :param starttime: Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.
        :type starttime: int
        :param target: Receiver email address filter.
        :type target: str
        :param xfilter: Only include mails containing this filter string.
        :type xfilter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_mails_serialize(
            node=node,
            endtime=endtime,
            var_from=var_from,
            greylist=greylist,
            ndr=ndr,
            starttime=starttime,
            target=target,
            xfilter=xfilter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NodesTrackerListMailsResponse",
            '400': "PmgError",
            '401': "PmgError",
            '403': "PmgError",
            '404': "PmgError",
            '500': "PmgError",
            '501': "PmgError",
            '503': "PmgError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_mails_without_preload_content(
        self,
        node: Annotated[str, Field(strict=True, description="The cluster node name.")],
        endtime: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.")] = None,
        var_from: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]], Field(description="Sender email address filter.")] = None,
        greylist: Annotated[Optional[Any], Field(description="Include Greylisted entries.")] = None,
        ndr: Annotated[Optional[Any], Field(description="Include NDRs (non delivery reports).")] = None,
        starttime: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.")] = None,
        target: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]], Field(description="Receiver email address filter.")] = None,
        xfilter: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]], Field(description="Only include mails containing this filter string.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Read mail list

        Read mail list.

        :param node: The cluster node name. (required)
        :type node: str
        :param endtime: Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.
        :type endtime: int
        :param var_from: Sender email address filter.
        :type var_from: str
        :param greylist: Include Greylisted entries.
        :type greylist: PmgBoolean
        :param ndr: Include NDRs (non delivery reports).
        :type ndr: PmgBoolean
        :param starttime: Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.
        :type starttime: int
        :param target: Receiver email address filter.
        :type target: str
        :param xfilter: Only include mails containing this filter string.
        :type xfilter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_mails_serialize(
            node=node,
            endtime=endtime,
            var_from=var_from,
            greylist=greylist,
            ndr=ndr,
            starttime=starttime,
            target=target,
            xfilter=xfilter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NodesTrackerListMailsResponse",
            '400': "PmgError",
            '401': "PmgError",
            '403': "PmgError",
            '404': "PmgError",
            '500': "PmgError",
            '501': "PmgError",
            '503': "PmgError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_mails_serialize(
        self,
        node,
        endtime,
        var_from,
        greylist,
        ndr,
        starttime,
        target,
        xfilter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if node is not None:
            _path_params['node'] = node
        # process the query parameters
        if endtime is not None:
            
            _query_params.append(('endtime', endtime))
            
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if greylist is not None:
            
            _query_params.append(('greylist', greylist.value))
            
        if ndr is not None:
            
            _query_params.append(('ndr', ndr.value))
            
        if starttime is not None:
            
            _query_params.append(('starttime', starttime))
            
        if target is not None:
            
            _query_params.append(('target', target))
            
        if xfilter is not None:
            
            _query_params.append(('xfilter', xfilter))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'PMGAuthCookie', 
            'PMGApiToken', 
            'CSRFPreventionToken'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/nodes/{node}/tracker',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def maillog(
        self,
        id: Annotated[str, Field(min_length=3, strict=True, max_length=64, description="Mail ID (as returned by the list API).")],
        node: Annotated[str, Field(strict=True, description="The cluster node name.")],
        endtime: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.")] = None,
        starttime: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NodesTrackerMaillogResponse:
        """Get the detailed syslog entries for a specific mail ID

        Get the detailed syslog entries for a specific mail ID.

        :param id: Mail ID (as returned by the list API). (required)
        :type id: str
        :param node: The cluster node name. (required)
        :type node: str
        :param endtime: Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.
        :type endtime: int
        :param starttime: Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.
        :type starttime: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._maillog_serialize(
            id=id,
            node=node,
            endtime=endtime,
            starttime=starttime,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NodesTrackerMaillogResponse",
            '400': "PmgError",
            '401': "PmgError",
            '403': "PmgError",
            '404': "PmgError",
            '500': "PmgError",
            '501': "PmgError",
            '503': "PmgError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def maillog_with_http_info(
        self,
        id: Annotated[str, Field(min_length=3, strict=True, max_length=64, description="Mail ID (as returned by the list API).")],
        node: Annotated[str, Field(strict=True, description="The cluster node name.")],
        endtime: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.")] = None,
        starttime: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NodesTrackerMaillogResponse]:
        """Get the detailed syslog entries for a specific mail ID

        Get the detailed syslog entries for a specific mail ID.

        :param id: Mail ID (as returned by the list API). (required)
        :type id: str
        :param node: The cluster node name. (required)
        :type node: str
        :param endtime: Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.
        :type endtime: int
        :param starttime: Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.
        :type starttime: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._maillog_serialize(
            id=id,
            node=node,
            endtime=endtime,
            starttime=starttime,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NodesTrackerMaillogResponse",
            '400': "PmgError",
            '401': "PmgError",
            '403': "PmgError",
            '404': "PmgError",
            '500': "PmgError",
            '501': "PmgError",
            '503': "PmgError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def maillog_without_preload_content(
        self,
        id: Annotated[str, Field(min_length=3, strict=True, max_length=64, description="Mail ID (as returned by the list API).")],
        node: Annotated[str, Field(strict=True, description="The cluster node name.")],
        endtime: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.")] = None,
        starttime: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get the detailed syslog entries for a specific mail ID

        Get the detailed syslog entries for a specific mail ID.

        :param id: Mail ID (as returned by the list API). (required)
        :type id: str
        :param node: The cluster node name. (required)
        :type node: str
        :param endtime: Only consider entries older than 'endtime' (unix epoch). This is set to '<start> + 1day' by default.
        :type endtime: int
        :param starttime: Only consider entries newer than 'starttime' (unix epoch). Default is 'now - 1day'.
        :type starttime: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._maillog_serialize(
            id=id,
            node=node,
            endtime=endtime,
            starttime=starttime,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NodesTrackerMaillogResponse",
            '400': "PmgError",
            '401': "PmgError",
            '403': "PmgError",
            '404': "PmgError",
            '500': "PmgError",
            '501': "PmgError",
            '503': "PmgError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _maillog_serialize(
        self,
        id,
        node,
        endtime,
        starttime,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        if node is not None:
            _path_params['node'] = node
        # process the query parameters
        if endtime is not None:
            
            _query_params.append(('endtime', endtime))
            
        if starttime is not None:
            
            _query_params.append(('starttime', starttime))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'PMGAuthCookie', 
            'PMGApiToken', 
            'CSRFPreventionToken'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/nodes/{node}/tracker/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


