# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pmg.models.pmg_access_auth_realm_type_enum import PmgAccessAuthRealmTypeEnum
from clientapi_pmg.models.pmg_autocreate_role_assignment_field import PmgAutocreateRoleAssignmentField
from clientapi_pmg.models.pmg_autocreate_role_enum import PmgAutocreateRoleEnum
from clientapi_pmg.models.pmg_boolean import PmgBoolean
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccessAuthRealmCreateAuthRealmRequest(BaseModel):
    """
    AccessAuthRealmCreateAuthRealmRequest
    """ # noqa: E501

    acr_values: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Specifies the Authentication Context Class Reference values that theAuthorization Server is being requested to use for the Auth Request.", alias="acr-values")

    autocreate: Optional[PmgBoolean] = Field(default=None, description="Automatically create users if they do not exist.")

    autocreate_role: Optional[PmgAutocreateRoleEnum] = Field(default=None, description="Automatically create users with a specific role. NOTE: Deprecated, favor 'autocreate-role-assignment'", alias="autocreate-role")

    autocreate_role_assignment: Optional[PmgAutocreateRoleAssignmentField] = Field(default=None, description="Defines which role should be assigned to auto-created users.", alias="autocreate-role-assignment")

    client_id: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="OpenID Connect Client ID", alias="client-id")

    client_key: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="OpenID Connect Client Key", alias="client-key")

    comment: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Description.")

    default: Optional[PmgBoolean] = Field(default=None, description="Use this as default realm")

    issuer_url: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="OpenID Connect Issuer Url", alias="issuer-url")

    prompt: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Specifies whether the Authorization Server prompts the End-User for reauthentication and consent.")

    realm: Annotated[str, Field(strict=True, max_length=32)] = Field(description="Authentication domain ID")

    scopes: Optional[Annotated[str, Field(strict=True)]] = Field(default='email profile', description="Specifies the scopes (user details) that should be authorized and returned, for example 'email' or 'profile'.")

    type: PmgAccessAuthRealmTypeEnum = Field(description="Realm type.")

    username_claim: Optional[Annotated[str, Field(strict=True)]] = Field(default='sub', description="OpenID Connect claim used to generate the unique username.", alias="username-claim")

    __properties: ClassVar[List[str]] = ["acr-values", "autocreate", "autocreate-role", "autocreate-role-assignment", "client-id", "client-key", "comment", "default", "issuer-url", "prompt", "realm", "scopes", "type", "username-claim"]


    @field_validator('acr_values')
    def acr_values_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:^[a-zA-Z0-9._:-]+$)", value):
            raise ValueError(r"must validate the regular expression /(?:^[a-zA-Z0-9._:-]+$)/")
        return value





    @field_validator('client_id')
    def client_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:^[\x20-\x7E]+$)", value):
            raise ValueError(r"must validate the regular expression /(?:^[\x20-\x7E]+$)/")
        return value


    @field_validator('client_key')
    def client_key_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:^[\x20-\x7E]+$)", value):
            raise ValueError(r"must validate the regular expression /(?:^[\x20-\x7E]+$)/")
        return value




    @field_validator('issuer_url')
    def issuer_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:^(https?):\/\/([a-zA-Z0-9.-]+)(:[0-9]{1,5})?(\/[^\s]*)?$)", value):
            raise ValueError(r"must validate the regular expression /(?:^(https?):\/\/([a-zA-Z0-9.-]+)(:[0-9]{1,5})?(\/[^\s]*)?$)/")
        return value


    @field_validator('prompt')
    def prompt_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:none|login|consent|select_account|\S+)", value):
            raise ValueError(r"must validate the regular expression /(?:none|login|consent|select_account|\S+)/")
        return value



    @field_validator('scopes')
    def scopes_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:^[a-zA-Z0-9._:-]+$)", value):
            raise ValueError(r"must validate the regular expression /(?:^[a-zA-Z0-9._:-]+$)/")
        return value



    @field_validator('username_claim')
    def username_claim_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:^[a-zA-Z0-9._:-]+$)", value):
            raise ValueError(r"must validate the regular expression /(?:^[a-zA-Z0-9._:-]+$)/")
        return value



    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccessAuthRealmCreateAuthRealmRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        # override the default output from pydantic by calling `to_dict()` of autocreate_role_assignment
        if self.autocreate_role_assignment:
            _dict['autocreate-role-assignment'] = self.autocreate_role_assignment.to_dict()
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccessAuthRealmCreateAuthRealmRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acr-values": obj.get("acr-values"),
            "autocreate": obj.get("autocreate"),
            "autocreate-role": obj.get("autocreate-role"),
            "autocreate-role-assignment": PmgAutocreateRoleAssignmentField.from_dict(obj["autocreate-role-assignment"]) if obj.get("autocreate-role-assignment") is not None else None,
            "client-id": obj.get("client-id"),
            "client-key": obj.get("client-key"),
            "comment": obj.get("comment"),
            "default": obj.get("default"),
            "issuer-url": obj.get("issuer-url"),
            "prompt": obj.get("prompt"),
            "realm": obj.get("realm"),
            "scopes": obj.get("scopes") if obj.get("scopes") is not None else 'email profile',
            "type": obj.get("type"),
            "username-claim": obj.get("username-claim") if obj.get("username-claim") is not None else 'sub'
        })
        return _obj


