# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pmg.models.pmg_boolean import PmgBoolean
from clientapi_pmg.models.pmg_notify_enum import PmgNotifyEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigPbsGetPbsResponseDataInner(BaseModel):
    """
    ConfigPbsGetPbsResponseDataInner
    """ # noqa: E501

    datastore: Annotated[str, Field(strict=True)] = Field(description="Proxmox Backup Server datastore name.")

    disable: Optional[PmgBoolean] = Field(default=None, description="Flag to disable (deactivate) the entry.")

    fingerprint: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Certificate SHA 256 fingerprint.")

    include_statistics: Optional[PmgBoolean] = Field(default=None, description="Include statistics in scheduled backups", alias="include-statistics")

    keep_daily: Optional[StrictInt] = Field(default=None, description="Keep backups for the last <N> different days. If there is more than one backup for a single day, only the latest one is kept.", alias="keep-daily")

    keep_hourly: Optional[StrictInt] = Field(default=None, description="Keep backups for the last <N> different hours. If there is more than one backup for a single hour, only the latest one is kept.", alias="keep-hourly")

    keep_last: Optional[StrictInt] = Field(default=None, description="Keep the last <N> backups.", alias="keep-last")

    keep_monthly: Optional[StrictInt] = Field(default=None, description="Keep backups for the last <N> different months. If there is more than one backup for a single month, only the latest one is kept.", alias="keep-monthly")

    keep_weekly: Optional[StrictInt] = Field(default=None, description="Keep backups for the last <N> different weeks. If there ismore than one backup for a single week, only the latest one is kept.", alias="keep-weekly")

    keep_yearly: Optional[StrictInt] = Field(default=None, description="Keep backups for the last <N> different years. If there is more than one backup for a single year, only the latest one is kept.", alias="keep-yearly")

    namespace: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Proxmox Backup Server namespace in the datastore, defaults to the root NS.")

    notify: Optional[PmgNotifyEnum] = Field(default=None, description="Specify when to notify via e-mail")

    password: Optional[StrictStr] = Field(default=None, description="Password or API token secret for the user on the Proxmox Backup Server.")

    port: Optional[Annotated[int, Field(le=65535, strict=True, ge=1)]] = Field(default=8007, description="Non-default port for Proxmox Backup Server.")

    remote: Annotated[str, Field(strict=True)] = Field(description="Proxmox Backup Server ID.")

    server: Annotated[str, Field(strict=True, max_length=256)] = Field(description="Proxmox Backup Server address.")

    username: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=512)]] = Field(default=None, description="Username or API token ID on the Proxmox Backup Server")

    __properties: ClassVar[List[str]] = ["datastore", "disable", "fingerprint", "include-statistics", "keep-daily", "keep-hourly", "keep-last", "keep-monthly", "keep-weekly", "keep-yearly", "namespace", "notify", "password", "port", "remote", "server", "username"]


    @field_validator('datastore')
    def datastore_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)", value):
            raise ValueError(r"must validate the regular expression /(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)/")
        return value



    @field_validator('fingerprint')
    def fingerprint_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}", value):
            raise ValueError(r"must validate the regular expression /([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}/")
        return value









    @field_validator('namespace')
    def namespace_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)\/){0,7}(?:(?:[A-Za-z0-9_][A-Za-z0-9._\-]*))?", value):
            raise ValueError(r"must validate the regular expression /(?:(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)\/){0,7}(?:(?:[A-Za-z0-9_][A-Za-z0-9._\-]*))?/")
        return value





    @field_validator('remote')
    def remote_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z][A-Za-z0-9_]*$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z][A-Za-z0-9_]*$/")
        return value


    @field_validator('server')
    def server_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)*)$/")
        return value


    @field_validator('username')
    def username_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:[^\s\\@]+\@[^\s\/\\@]+)", value):
            raise ValueError(r"must validate the regular expression /(?:[^\s\\@]+\@[^\s\/\\@]+)/")
        return value



    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigPbsGetPbsResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigPbsGetPbsResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "datastore": obj.get("datastore"),
            "disable": obj.get("disable"),
            "fingerprint": obj.get("fingerprint"),
            "include-statistics": obj.get("include-statistics"),
            "keep-daily": obj.get("keep-daily"),
            "keep-hourly": obj.get("keep-hourly"),
            "keep-last": obj.get("keep-last"),
            "keep-monthly": obj.get("keep-monthly"),
            "keep-weekly": obj.get("keep-weekly"),
            "keep-yearly": obj.get("keep-yearly"),
            "namespace": obj.get("namespace"),
            "notify": obj.get("notify"),
            "password": obj.get("password"),
            "port": obj.get("port") if obj.get("port") is not None else 8007,
            "remote": obj.get("remote"),
            "server": obj.get("server"),
            "username": obj.get("username")
        })
        return _obj


