# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pmg.models.pmg_boolean import PmgBoolean
from clientapi_pmg.models.pmg_mode_enum import PmgModeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigLdapUpdateConfigRequest(BaseModel):
    """
    ConfigLdapUpdateConfigRequest
    """ # noqa: E501

    accountattr: Optional[StrictStr] = Field(default='sAMAccountName, uid', description="Account attribute name name.")

    basedn: Optional[StrictStr] = Field(default=None, description="Base domain name.")

    binddn: Optional[StrictStr] = Field(default=None, description="Bind domain name.")

    bindpw: Optional[StrictStr] = Field(default=None, description="Bind password.")

    cafile: Optional[StrictStr] = Field(default=None, description="Path to CA file. Only useful with option 'verify'")

    comment: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Description.")

    delete: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="A list of settings you want to delete.")

    digest: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.")

    disable: Optional[PmgBoolean] = Field(default=None, description="Flag to disable/deactivate the entry.")

    filter: Optional[StrictStr] = Field(default=None, description="LDAP filter.")

    groupbasedn: Optional[StrictStr] = Field(default=None, description="Base domain name for groups.")

    groupclass: Optional[StrictStr] = Field(default='group, univentionGroup, ipausergroup', description="List of objectclasses for groups.")

    mailattr: Optional[StrictStr] = Field(default='mail, userPrincipalName, proxyAddresses, othermailbox, mailAlternativeAddress', description="List of mail attribute names.")

    mode: Optional[PmgModeEnum] = Field(default=None, description="LDAP protocol mode ('ldap', 'ldaps' or 'ldap+starttls').")

    port: Optional[Annotated[int, Field(le=65535, strict=True, ge=1)]] = Field(default=None, description="Specify the port to connect to.")

    server1: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Server address.")

    server2: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Fallback server address. Userd when the first server is not available.")

    verify: Optional[PmgBoolean] = Field(default=None, description="Verify server certificate. Only useful with ldaps or ldap+starttls.")

    __properties: ClassVar[List[str]] = ["accountattr", "basedn", "binddn", "bindpw", "cafile", "comment", "delete", "digest", "disable", "filter", "groupbasedn", "groupclass", "mailattr", "mode", "port", "server1", "server2", "verify"]

















    @field_validator('server1')
    def server1_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)*)$/")
        return value


    @field_validator('server2')
    def server2_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)*)$/")
        return value




    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigLdapUpdateConfigRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigLdapUpdateConfigRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accountattr": obj.get("accountattr") if obj.get("accountattr") is not None else 'sAMAccountName, uid',
            "basedn": obj.get("basedn"),
            "binddn": obj.get("binddn"),
            "bindpw": obj.get("bindpw"),
            "cafile": obj.get("cafile"),
            "comment": obj.get("comment"),
            "delete": obj.get("delete"),
            "digest": obj.get("digest"),
            "disable": obj.get("disable"),
            "filter": obj.get("filter"),
            "groupbasedn": obj.get("groupbasedn"),
            "groupclass": obj.get("groupclass") if obj.get("groupclass") is not None else 'group, univentionGroup, ipausergroup',
            "mailattr": obj.get("mailattr") if obj.get("mailattr") is not None else 'mail, userPrincipalName, proxyAddresses, othermailbox, mailAlternativeAddress',
            "mode": obj.get("mode"),
            "port": obj.get("port"),
            "server1": obj.get("server1"),
            "server2": obj.get("server2"),
            "verify": obj.get("verify")
        })
        return _obj


