# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pmg.models.pmg_boolean import PmgBoolean
from clientapi_pmg.models.pmg_config_mail_protocol_enum import PmgConfigMailProtocolEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigTransportWriteRequest(BaseModel):
    """
    ConfigTransportWriteRequest
    """ # noqa: E501

    comment: Optional[StrictStr] = Field(default=None, description="Comment.")

    host: Optional[StrictStr] = Field(default=None, description="Target host (name or IP address).")

    port: Optional[Annotated[int, Field(le=65535, strict=True, ge=1)]] = Field(default=None, description="Transport port.")

    protocol: Optional[PmgConfigMailProtocolEnum] = Field(default=None, description="Transport protocol.")

    use_mx: Optional[PmgBoolean] = Field(default=None, description="Enable MX lookups (SMTP).")

    __properties: ClassVar[List[str]] = ["comment", "host", "port", "protocol", "use_mx"]








    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigTransportWriteRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigTransportWriteRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment": obj.get("comment"),
            "host": obj.get("host"),
            "port": obj.get("port"),
            "protocol": obj.get("protocol"),
            "use_mx": obj.get("use_mx")
        })
        return _obj


