# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pmg.models.pmg_boolean import PmgBoolean
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigSpamUpdateSpamSectionRequest(BaseModel):
    """
    ConfigSpamUpdateSpamSectionRequest
    """ # noqa: E501

    bounce_score: Optional[Annotated[int, Field(le=1000, strict=True, ge=0)]] = Field(default=0, description="Additional score for bounce mails.")

    clamav_heuristic_score: Optional[Annotated[int, Field(le=1000, strict=True, ge=0)]] = Field(default=3, description="Score for ClamAV heuristics (Encrypted Archives/Documents, PhishingScanURLs, ...).")

    delete: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="A list of settings you want to delete.")

    digest: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.")

    extract_text: Optional[PmgBoolean] = Field(default=None, description="Extract text from attachments (doc, pdf, rtf, images) and scan for spam.")

    languages: Optional[Annotated[str, Field(strict=True)]] = Field(default='all', description="This option is used to specify which languages are considered OK for incoming mail.")

    maxspamsize: Optional[Annotated[int, Field(strict=True, ge=64)]] = Field(default=262144, description="Maximum size of spam messages in bytes.")

    rbl_checks: Optional[PmgBoolean] = Field(default=None, description="Enable real time blocklists (RBL) checks.")

    use_awl: Optional[PmgBoolean] = Field(default=None, description="Use the Auto-Welcomelist plugin.")

    use_bayes: Optional[PmgBoolean] = Field(default=None, description="Whether to use the naive-Bayesian-style classifier.")

    use_razor: Optional[PmgBoolean] = Field(default=None, description="Whether to use Razor2, if it is available.")

    wl_bounce_relays: Optional[StrictStr] = Field(default=None, description="Welcomelist legitimate bounce relays.")

    __properties: ClassVar[List[str]] = ["bounce_score", "clamav_heuristic_score", "delete", "digest", "extract_text", "languages", "maxspamsize", "rbl_checks", "use_awl", "use_bayes", "use_razor", "wl_bounce_relays"]







    @field_validator('languages')
    def languages_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(all|([a-z][a-z])+( ([a-z][a-z])+)*)", value):
            raise ValueError(r"must validate the regular expression /(all|([a-z][a-z])+( ([a-z][a-z])+)*)/")
        return value









    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigSpamUpdateSpamSectionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigSpamUpdateSpamSectionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bounce_score": obj.get("bounce_score") if obj.get("bounce_score") is not None else 0,
            "clamav_heuristic_score": obj.get("clamav_heuristic_score") if obj.get("clamav_heuristic_score") is not None else 3,
            "delete": obj.get("delete"),
            "digest": obj.get("digest"),
            "extract_text": obj.get("extract_text"),
            "languages": obj.get("languages") if obj.get("languages") is not None else 'all',
            "maxspamsize": obj.get("maxspamsize") if obj.get("maxspamsize") is not None else 262144,
            "rbl_checks": obj.get("rbl_checks"),
            "use_awl": obj.get("use_awl"),
            "use_bayes": obj.get("use_bayes"),
            "use_razor": obj.get("use_razor"),
            "wl_bounce_relays": obj.get("wl_bounce_relays")
        })
        return _obj


