# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pmg.models.pmg_boolean import PmgBoolean
from clientapi_pmg.models.pmg_config_admin_dkim_use_domain_enum import PmgConfigAdminDkimUseDomainEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigAdminUpdateAdminSectionRequest(BaseModel):
    """
    ConfigAdminUpdateAdminSectionRequest
    """ # noqa: E501

    admin_mail_from: Optional[Annotated[str, Field(strict=True)]] = Field(default='Proxmox Mail Gateway <postmaster>', description="Text for 'From' header in admin mails and bounces.", alias="admin-mail-from")

    advfilter: Optional[PmgBoolean] = Field(default=None, description="Enable advanced filters for statistic.  If this is enabled, the receiver statistic are limited to active ones (receivers which also sent out mail in the 90 days before), and the contact statistic will not contain these active receivers. ")

    avast: Optional[PmgBoolean] = Field(default=None, description="Use Avast Virus Scanner (/usr/bin/scan). You need to buy and install 'Avast Core Security' before you can enable this feature.")

    clamav: Optional[PmgBoolean] = Field(default=None, description="Use ClamAV Virus Scanner. This is the default virus scanner and is enabled by default.")

    custom_check: Optional[PmgBoolean] = Field(default=None, description="Use Custom Check Script. The script has to take the defined arguments and can return Virus findings or a Spamscore.")

    custom_check_path: Optional[Annotated[str, Field(strict=True)]] = Field(default='/usr/local/bin/pmg-custom-check', description="Absolute Path to the Custom Check Script")

    dailyreport: Optional[PmgBoolean] = Field(default=None, description="Send daily reports.")

    delete: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="A list of settings you want to delete.")

    demo: Optional[PmgBoolean] = Field(default=None, description="Demo mode - do not start SMTP filter.")

    digest: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.")

    dkim_use_domain: Optional[PmgConfigAdminDkimUseDomainEnum] = Field(default=None, description="Whether to sign using the domain found in the header or the envelope.", alias="dkim-use-domain")

    dkim_selector: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Default DKIM selector")

    dkim_sign: Optional[PmgBoolean] = Field(default=None, description="DKIM sign outbound mails with the configured Selector.")

    dkim_sign_all_mail: Optional[PmgBoolean] = Field(default=None, description="DKIM sign all outgoing mails irrespective of the Envelope From domain.")

    email: Optional[Annotated[str, Field(strict=True)]] = Field(default='admin@domain.tld', description="Administrator E-Mail address.")

    http_proxy: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Specify external http proxy which is used for downloads (example: 'http://username:password@host:port/')")

    statlifetime: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=7, description="User Statistics Lifetime (days)")

    __properties: ClassVar[List[str]] = ["admin-mail-from", "advfilter", "avast", "clamav", "custom_check", "custom_check_path", "dailyreport", "delete", "demo", "digest", "dkim-use-domain", "dkim_selector", "dkim_sign", "dkim_sign_all_mail", "email", "http_proxy", "statlifetime"]


    @field_validator('admin_mail_from')
    def admin_mail_from_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^\p{PosixPrint}{1,998}$", value):
            raise ValueError(r"must validate the regular expression /^\p{PosixPrint}{1,998}$/")
        return value






    @field_validator('custom_check_path')
    def custom_check_path_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^\/([^\/\0]+\/)+[^\/\0]+$", value):
            raise ValueError(r"must validate the regular expression /^\/([^\/\0]+\/)+[^\/\0]+$/")
        return value







    @field_validator('dkim_selector')
    def dkim_selector_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)(?:\.[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)*$", value):
            raise ValueError(r"must validate the regular expression /^(?:[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)(?:\.[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)*$/")
        return value




    @field_validator('email')
    def email_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[^\s@]+@[^\s@]+\.[^\s@]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s@]+@[^\s@]+\.[^\s@]+$/")
        return value


    @field_validator('http_proxy')
    def http_proxy_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"http:\/\/.*", value):
            raise ValueError(r"must validate the regular expression /http:\/\/.*/")
        return value




    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigAdminUpdateAdminSectionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigAdminUpdateAdminSectionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "admin-mail-from": obj.get("admin-mail-from") if obj.get("admin-mail-from") is not None else 'Proxmox Mail Gateway <postmaster>',
            "advfilter": obj.get("advfilter"),
            "avast": obj.get("avast"),
            "clamav": obj.get("clamav"),
            "custom_check": obj.get("custom_check"),
            "custom_check_path": obj.get("custom_check_path") if obj.get("custom_check_path") is not None else '/usr/local/bin/pmg-custom-check',
            "dailyreport": obj.get("dailyreport"),
            "delete": obj.get("delete"),
            "demo": obj.get("demo"),
            "digest": obj.get("digest"),
            "dkim-use-domain": obj.get("dkim-use-domain"),
            "dkim_selector": obj.get("dkim_selector"),
            "dkim_sign": obj.get("dkim_sign"),
            "dkim_sign_all_mail": obj.get("dkim_sign_all_mail"),
            "email": obj.get("email") if obj.get("email") is not None else 'admin@domain.tld',
            "http_proxy": obj.get("http_proxy"),
            "statlifetime": obj.get("statlifetime") if obj.get("statlifetime") is not None else 7
        })
        return _obj


