# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clientapi_pmg.models.pmg_boolean import PmgBoolean
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigTfaGetWebauthnConfigResponseData(BaseModel):
    """
    ConfigTfaGetWebauthnConfigResponseData
    """ # noqa: E501

    allow_subdomains: Optional[PmgBoolean] = Field(default=None, description="Whether to allow the origin to be a subdomain, rather than the exact URL.", alias="allow-subdomains")

    id: Optional[StrictStr] = Field(default=None, description="Relying part ID. Must be the domain name without protocol, port or location. Changing this *will* break existing credentials.")

    origin: Optional[StrictStr] = Field(default=None, description="Site origin. Must be a `https://` URL (or `http://localhost`). Should contain the address users type in their browsers to access the web interface. Changing this *may* break existing credentials.")

    rp: Optional[StrictStr] = Field(default=None, description="Relying party name. Any text identifier. Changing this *may* break existing credentials.")

    __properties: ClassVar[List[str]] = ["allow-subdomains", "id", "origin", "rp"]







    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigTfaGetWebauthnConfigResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigTfaGetWebauthnConfigResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allow-subdomains": obj.get("allow-subdomains"),
            "id": obj.get("id"),
            "origin": obj.get("origin"),
            "rp": obj.get("rp")
        })
        return _obj


