# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pmg.models.pmg_boolean import PmgBoolean
from clientapi_pmg.models.pmg_protocol_enum import PmgProtocolEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigFetchmailWriteRequest(BaseModel):
    """
    ConfigFetchmailWriteRequest
    """ # noqa: E501

    enable: Optional[PmgBoolean] = Field(default=None, description="Flag to enable or disable polling.")

    interval: Optional[Annotated[int, Field(le=2016, strict=True, ge=1)]] = Field(default=None, description="Only check this site every <interval> poll cycles. A poll cycle is 5 minutes.")

    keep: Optional[PmgBoolean] = Field(default=None, description="Keep retrieved messages on the remote mailserver.")

    var_pass: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="The password used tfor server login.", alias="pass")

    port: Optional[Annotated[int, Field(le=65535, strict=True, ge=1)]] = Field(default=None, description="Port number.")

    protocol: Optional[PmgProtocolEnum] = Field(default=None, description="Specify  the  protocol to use when communicating with the remote mailserver")

    server: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Server address (IP or DNS name).")

    ssl: Optional[PmgBoolean] = Field(default=None, description="Use SSL.")

    target: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=512)]] = Field(default=None, description="The target email address (where to deliver fetched mails).")

    user: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="The user identification to be used when logging in to the server")

    __properties: ClassVar[List[str]] = ["enable", "interval", "keep", "pass", "port", "protocol", "server", "ssl", "target", "user"]








    @field_validator('server')
    def server_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?)*)$/")
        return value



    @field_validator('target')
    def target_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:[^\s\\@]+\@[^\s\/\\@]+)", value):
            raise ValueError(r"must validate the regular expression /(?:[^\s\\@]+\@[^\s\/\\@]+)/")
        return value




    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigFetchmailWriteRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigFetchmailWriteRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enable": obj.get("enable"),
            "interval": obj.get("interval"),
            "keep": obj.get("keep"),
            "pass": obj.get("pass"),
            "port": obj.get("port"),
            "protocol": obj.get("protocol"),
            "server": obj.get("server"),
            "ssl": obj.get("ssl"),
            "target": obj.get("target"),
            "user": obj.get("user")
        })
        return _obj


