# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from clientapi_pmg.models.nodes_status_status_response_data_boot_info import NodesStatusStatusResponseDataBootInfo
from clientapi_pmg.models.nodes_status_status_response_data_current_kernel import NodesStatusStatusResponseDataCurrentKernel
from clientapi_pmg.models.pmg_boolean import PmgBoolean
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NodesStatusStatusResponseData(BaseModel):
    """
    NodesStatusStatusResponseData
    """ # noqa: E501

    boot_info: NodesStatusStatusResponseDataBootInfo = Field(alias="boot-info")

    current_kernel: NodesStatusStatusResponseDataCurrentKernel = Field(alias="current-kernel")

    insync: PmgBoolean = Field(description="Database is synced with other nodes.")

    time: Annotated[int, Field(strict=True, ge=1297163644)] = Field(description="Seconds since 1970-01-01 00:00:00 UTC.")

    uptime: Annotated[int, Field(strict=True, ge=0)] = Field(description="The uptime of the system in seconds.")

    __properties: ClassVar[List[str]] = ["boot-info", "current-kernel", "insync", "time", "uptime"]








    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodesStatusStatusResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of boot_info
        if self.boot_info:
            _dict['boot-info'] = self.boot_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of current_kernel
        if self.current_kernel:
            _dict['current-kernel'] = self.current_kernel.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodesStatusStatusResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "boot-info": NodesStatusStatusResponseDataBootInfo.from_dict(obj["boot-info"]) if obj.get("boot-info") is not None else None,
            "current-kernel": NodesStatusStatusResponseDataCurrentKernel.from_dict(obj["current-kernel"]) if obj.get("current-kernel") is not None else None,
            "insync": obj.get("insync"),
            "time": obj.get("time"),
            "uptime": obj.get("uptime")
        })
        return _obj


