# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NodesTrackerMaillogResponseData(BaseModel):
    """
    NodesTrackerMaillogResponseData
    """ # noqa: E501

    client: Optional[StrictStr] = Field(default=None, description="Client address")

    dstatus: Annotated[str, Field(min_length=1, strict=True, max_length=1)] = Field(description="Delivery status.")

    var_from: StrictStr = Field(description="Sender email address.", alias="from")

    id: StrictStr = Field(description="Unique ID.")

    logs: List[StrictStr]

    msgid: Optional[StrictStr] = Field(default=None, description="SMTP message ID.")

    qid: Optional[StrictStr] = Field(default=None, description="Postfix qmgr ID.")

    relay: Optional[StrictStr] = Field(default=None, description="ID of relayed mail.")

    rstatus: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=1)]] = Field(default=None, description="Delivery status of relayed mail.")

    size: Optional[Union[float, int]] = Field(default=None, description="The size of the raw email.")

    time: int = Field(description="Delivery timestamp.")

    to: StrictStr = Field(description="Receiver email address.")

    __properties: ClassVar[List[str]] = ["client", "dstatus", "from", "id", "logs", "msgid", "qid", "relay", "rstatus", "size", "time", "to"]















    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodesTrackerMaillogResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodesTrackerMaillogResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "client": obj.get("client"),
            "dstatus": obj.get("dstatus"),
            "from": obj.get("from"),
            "id": obj.get("id"),
            "logs": obj.get("logs"),
            "msgid": obj.get("msgid"),
            "qid": obj.get("qid"),
            "relay": obj.get("relay"),
            "rstatus": obj.get("rstatus"),
            "size": obj.get("size"),
            "time": obj.get("time"),
            "to": obj.get("to")
        })
        return _obj


