# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PmgServiceEnum(str, Enum):
    """
    PmgServiceEnum
    """

    """
    allowed enum values
    """
    CLAMAV_MINUS_DAEMON = 'clamav-daemon'
    CLAMAV_MINUS_FRESHCLAM = 'clamav-freshclam'
    FETCHMAIL = 'fetchmail'
    PMGPROXY = 'pmgproxy'
    PMGDAEMON = 'pmgdaemon'
    PMGPOLICY = 'pmgpolicy'
    PMG_MINUS_SMTP_MINUS_FILTER = 'pmg-smtp-filter'
    PMGTUNNEL = 'pmgtunnel'
    PMGMIRROR = 'pmgmirror'
    SSH = 'ssh'
    RSYSLOG = 'rsyslog'
    POSTFIX = 'postfix'
    POSTGRES = 'postgres'
    SYSTEMD_MINUS_TIMESYNCD = 'systemd-timesyncd'
    PMG_MINUS_HOURLY = 'pmg-hourly'
    PMG_MINUS_DAILY = 'pmg-daily'
    PMGREPORT = 'pmgreport'
    PMGSPAMREPORT = 'pmgspamreport'
    CHRONY = 'chrony'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PmgServiceEnum from a JSON string"""
        return cls(json.loads(json_str))


