# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PmgConfigTfaDeleteEnum(str, Enum):
    """
    PmgConfigTfaDeleteEnum
    """

    """
    allowed enum values
    """
    ALLOW_MINUS_SUBDOMAINS = 'allow-subdomains'
    ID = 'id'
    ORIGIN = 'origin'
    RP = 'rp'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PmgConfigTfaDeleteEnum from a JSON string"""
        return cls(json.loads(json_str))


