# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QuarantineAttachmentResponseDataInner(BaseModel):
    """
    QuarantineAttachmentResponseDataInner
    """ # noqa: E501

    bytes: StrictInt = Field(description="Size of raw email.")

    envelope_sender: StrictStr = Field(description="SMTP envelope sender.")

    var_from: StrictStr = Field(description="Header 'From' field.", alias="from")

    id: StrictStr = Field(description="Unique ID")

    receiver: StrictStr = Field(description="Receiver email address")

    sender: Optional[StrictStr] = Field(default=None, description="Header 'Sender' field.")

    subject: StrictStr = Field(description="Header 'Subject' field.")

    time: StrictInt = Field(description="Receive time stamp")

    __properties: ClassVar[List[str]] = ["bytes", "envelope_sender", "from", "id", "receiver", "sender", "subject", "time"]











    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuarantineAttachmentResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuarantineAttachmentResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bytes": obj.get("bytes"),
            "envelope_sender": obj.get("envelope_sender"),
            "from": obj.get("from"),
            "id": obj.get("id"),
            "receiver": obj.get("receiver"),
            "sender": obj.get("sender"),
            "subject": obj.get("subject"),
            "time": obj.get("time")
        })
        return _obj


