# coding: utf-8

"""
    Proxmox Mail Gateway API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StatisticsMaildistributionResponseDataInner(BaseModel):
    """
    StatisticsMaildistributionResponseDataInner
    """ # noqa: E501

    bounces_in: Union[StrictFloat, StrictInt] = Field(description="Incoming bounce mail count (sender = <>).")

    bounces_out: Union[StrictFloat, StrictInt] = Field(description="Outgoing bounce mail count (sender = <>).")

    count: Union[StrictFloat, StrictInt] = Field(description="Overall mail count (in and out).")

    count_in: Union[StrictFloat, StrictInt] = Field(description="Incoming mail count.")

    count_out: Union[StrictFloat, StrictInt] = Field(description="Outgoing mail count.")

    index: StrictInt = Field(description="Hour (0-23).")

    spamcount_in: Union[StrictFloat, StrictInt] = Field(description="Incoming spam mails (spamcount_in + glcount + spfcount).")

    spamcount_out: Union[StrictFloat, StrictInt] = Field(description="Outgoing spam mails.")

    viruscount_in: Union[StrictFloat, StrictInt] = Field(description="Number of incoming virus mails.")

    viruscount_out: Union[StrictFloat, StrictInt] = Field(description="Number of outgoing virus mails.")

    __properties: ClassVar[List[str]] = ["bounces_in", "bounces_out", "count", "count_in", "count_out", "index", "spamcount_in", "spamcount_out", "viruscount_in", "viruscount_out"]













    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatisticsMaildistributionResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatisticsMaildistributionResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bounces_in": obj.get("bounces_in"),
            "bounces_out": obj.get("bounces_out"),
            "count": obj.get("count"),
            "count_in": obj.get("count_in"),
            "count_out": obj.get("count_out"),
            "index": obj.get("index"),
            "spamcount_in": obj.get("spamcount_in"),
            "spamcount_out": obj.get("spamcount_out"),
            "viruscount_in": obj.get("viruscount_in"),
            "viruscount_out": obj.get("viruscount_out")
        })
        return _obj


